# Project 1

## Pseudo Code

### Environment

Classes:
Grid
    Constructor: create a blank 6x6 2D array
Shelves
    Constructor: populate a random shelf configuration
        Random numbers if its the same then try again.
Agent Location
    Constructor: Random starting location that isn't on a Shelf

### Agent

Customer Order
    Constructor: Generate random number 1 - 10 and pick random unique shelf combo
Sensors
    Roll for sensor detection
    Add fake shelf
    Remove real shelf
    Detect shelves
Agent function
      If any of the grid positions in its neighborhood refers to an item ordered, then it moves to that grid position. If two or more neighboring positions contain ordered items, then the tie is broken by making a random choice between the positions involved. 
      If none of the neighboring positions contain ordered items, then a random choice is made to move to the next node.
Agent State
    
    
Agent Actuator
    Move agent
        left 
        right
        up
        down
Agent Items
    List of all items collected so far

In [42]:
class agentFunction:
    
    
    
    def __init__(self, agentLocation, percept, customerOrder,acutator,randRange):
        self.location = agentLocation
        self.percept = percept
        self.order = customerOrder
        self.orderShelfLocations = []
        self.actuator = actuator
        self.random = randRange
        
        
        
    def setLocation(self,agentLocation):
        self.location = agentLocation
        
    def getLocation(self):
        return self.location
    
    def setPercept(self,percept):
        self.percept = percept
        
    def getPercept(self):
        return self.percept
    
    def addShelfLocation(self,location):
        self.orderShelfLocations.append(location)
        
    def getNextShelfLocation(self):
        return self.orderShelfLocations.pop(0)
    
    def getCurrentShelfLocation(self):
        return self.currentShelf
    
    def setCurrentShelfLocation(self,location):
        self.currentShelf = location
    #how to handle movement
    #have a current movement?
        
    def determineAction(self):
        if (self.percept.onOrderShelf()):
            self.actuator.collectItem()
            self.currentShelf = ""
        if (self.percept.shelfCount() == 0):
            if (len(self.orderShelfLocation) == 0):
                move = self.random(4)
                determineRandomMove(move)
            else:
                if (self.currentShelf != ""):
                    self.actuator.move(self.currentShelf)
                else:
                    setCurrentShelfLocation(getNextShelfLocation())
                    self.actuator.move(self.currentShelf)
        elif (self.percept.shelfCount() >= 1):
            shelfLocations = self.percept.getShelfLocations()
            for i in shelfLocations:
                self.addShelfLocation(i)
            self.actuator.move(getNextShelfLocation())
            
    
    def determineRandomMove(self,move):
        if (move == 0):
            self.actuator.left()
        elif (move == 1):
            self.actuator.right()
        elif (move == 2):
            self.actuator.up()
        elif (move == 3):
            self.actuator.down()
        
    #returns true if customer order is complete
    #def hasCollectedAllItems(self):
        


In [43]:
#import libraries
import numpy as np
import random
class Environment:
    
    def __init__(self):
        self.line_sep = '\n~~~~~~~~~~~~~~~~~~\n'

        #Define the environment
        self.environment_rows = 6
        self.environment_columns = 6
        self.item_A = 'A'
        self.item_B = 'B'
        self.item_C = 'C'
        self.item_D = 'D'
        self.item_E = 'E'
        self.item_F = 'F'
        self.item_G = 'G'
        self.item_H = 'H'
        self.item_I = 'I'
        self.item_J = 'J'
        
    def print_grid(self,rewards,ordered_items):
        #print itemes ordered
        print(self.line_sep)

        print('Items ordered:',ordered_items)

        print (self.line_sep)
            
        #Print rewards matrix
        for row in rewards:
            print(row)
            
        print(self.line_sep)
    
    def genRandOrder(self):
        x = random.randint(1,10)
        #Give items their single character name
        items = [self.item_A,self.item_B, self.item_C, self.item_D, self.item_E, self.item_F, self.item_G, self.item_H, self.item_I, self.item_J]
        
        #Generate random orders containing items A-J
        ordered_items = random.sample(items,x)
        return ordered_items
    
    #Define rewards
    def buildEnv(self):
        rewards = np.full((self.environment_rows, self.environment_columns), -1)
        ordered_items = self.genRandOrder()
        
        if self.item_A in ordered_items:
                rewards [1,1] = 3
        else:
            rewards[1,1] = -1

        if self.item_B in ordered_items:
            rewards [2,2] = 3
        else:
            rewards[2,2] = -1

        if self.item_C in ordered_items:
            rewards [3,1] = 3
        else:
            rewards[3,1] = -1

        if self.item_D in ordered_items:
            rewards [0,2] = 3
        else:
            rewards[0,2] = -1

        if self.item_E in ordered_items:
            rewards [2,0] = 3
        else:
            rewards[2,0] = -1

        if self.item_F in ordered_items:
            rewards [4,2] = 3
        else:
            rewards[4,2] = -1
            
        if self.item_G in ordered_items:
            rewards [1,4] = 3
        else:
            rewards[1,4] = -1

        if self.item_H in ordered_items:
            rewards [4,5] = 3
        else:
            rewards[4,5] = -1

        if self.item_I in ordered_items:
            rewards [2,4] = 3
        else:
            rewards[2,4] = -1
            
        if self.item_J in ordered_items:
            rewards [5,3] = 3
        else:
            rewards[5,3] = -1
        
        return rewards,ordered_items

    #need to build random layout case after static shelf testing to make sure agen works in any shelf situation.
    #def randomShelfOrganization(self):
        

    #agentLocation = rewards[0,0] = 0


In [44]:
class actuator:
    def __init__(self):
        print("a")
    def collectItem(self):
        print("a")
    def move(self):
        print("a")
    def left(self):
        print("a")
    def right(self):
        print("a")
    def up(self):
        print("a")
    def down(self):
        print("a")
    def addVisitedSpace(self):
        print("a")
        

In [178]:
class percept:
    def __init__(self,currentLocation, envArray):
        self.percepts = dict(left=dict(coord=[],value=""), right=dict(coord=[],value=""), up=dict(coord=[],value=""), down=dict(coord=[],value=""), current=dict(coord=[],value=""))
        self.currentLocation = currentLocation
        self.envArray = envArray
        
    def determine(self):
        
        self.percepts["current"]["coord"] = self.currentLocation
        self.percepts["current"]["value"] = self.envArray[self.currentLocation[0]][self.currentLocation[1]]
        
        if (self.currentLocation[0] == 0):
            self.percepts["up"]["coord"] = []
            self.percepts["up"]["value"] = ""
        else:
            self.percepts["up"]["coord"] = [(self.currentLocation[0]-1),self.currentLocation[1]]
            self.percepts["up"]["value"] = self.envArray[self.currentLocation[0]][self.currentLocation[1]]
        
        if (self.currentLocation[0] == 5):
            self.percepts["down"]["coord"] = []
            self.percepts["down"]["value"] = ""
        else:
            self.percepts["down"]["coord"] = [(self.currentLocation[0]+1),self.currentLocation[1]]
            self.percepts["down"]["value"] = self.envArray[self.currentLocation[0]][self.currentLocation[1]]
        
        if (self.currentLocation[1] == 0):
            self.percepts["left"]["coord"] = []
            self.percepts["left"]["value"] = ""
        else:
            self.percepts["left"]["coord"] = [self.currentLocation[0],(self.currentLocation[1]-1)]
            self.percepts["left"]["value"] = self.envArray[self.currentLocation[0]][self.currentLocation[1]]
        
        if (self.currentLocation[1] == 5):
            self.percepts["right"]["coord"] = []
            self.percepts["right"]["value"] = ""
        else:
            self.percepts["right"]["coord"] = [self.currentLocation[0],(self.currentLocation[1]+1)]
            self.percepts["right"]["value"] = self.envArray[self.currentLocation[0]][self.currentLocation[1]]
    
    def onOrderShelf(self):
        if (self.percepts["current"]["value"] == 3):
            return true;
        return false
    
    def shelfCount(self):
        count = 0
        for i in self.percepts:
            if i["value"] == 3:
                count = count + 1
        return count
        
    def getShelfLocations(self):
        shelves = []
        for i in self.percepts:
            if i["value"] == 3:
                shelves.append(i["coord"])
        return shelves
        
    def getPercepts(self):
        return self.percepts
    
    def setValue(self, key, value):
        self.percepts[key]['value'] = value
        
        

In [172]:
class sensor:
    def __init__(self, random, agentlocation,percept):
        self.random = random
        self.agentlocation = agentlocation
        self.percept = percept
        
    def sensorRoll(self):
        roll = self.random.randint(1,10)
        if roll == 9:
            percepts = self.percept.getPercepts()
            percepts = self.setEmptyShelf()   
        elif roll == 10:
            percepts = self.percept.getPercepts()
            percepts = self.setShelf()
            
    
    #need the percept to be an array of dictionaries
    def setEmptyShelf(self):
        shelves = []
        for i in self.percept.getPercepts():
            if (self.percept.getPercepts()[i]['value'] == 3):
                if(i != 'current'):
                    shelves.append(i)
        if (len(shelves) > 0):  
            roll = self.random.randint(0,(len(shelves)-1))
            key = shelves[roll]
            self.percept.setValue(key, -1) 
    
    def setShelf(self):
        empty = []
        for i in self.percept.getPercepts():
            if (self.percept.getPercepts()[i]['value'] == -1):
                if(i != 'current'):
                    empty.append(i)
        if (len(empty) > 0):    
            roll = self.random.randint(0,(len(empty)-1))
            key = empty[roll]
            self.percept.setValue(key, 3) 

In [113]:
class stats:
    def __init__(self, percept):
        self.percept = percept
        self.score = 0
        
    def updateScore(self):
        self.score = self.score + self.percept["current"]["value"]
        
    def getScore(self):
        return self.score

In [136]:
import random as rand
def main():
    env = Environment()
    warehouse,ordered_items = env.buildEnv()
    env.print_grid(warehouse,ordered_items)
    
    #agentLocation starts at 0,0 in first episode
    agentLocation = [0,0]
    prcpt = percept(agentLocation,warehouse)
    
    
    determine = prcpt.determine()
    snsr = sensor(rand, agentLocation, prcpt)
    snsr.sensorRoll()
    act = actuator()
    agent = agentFunction(agentLocation, pcrpt, ordered_items,act,rand)
    #while(!agent.hasCollectedAllItems()) {
    
    
    #}
    
if __name__ == "__main__":
    main()


~~~~~~~~~~~~~~~~~~

Items ordered: ['C', 'I', 'A', 'E', 'F', 'J', 'D', 'G']

~~~~~~~~~~~~~~~~~~

[-1 -1  3 -1 -1 -1]
[-1  3 -1 -1  3 -1]
[ 3 -1 -1 -1  3 -1]
[-1  3 -1 -1 -1 -1]
[-1 -1  3 -1 -1 -1]
[-1 -1 -1  3 -1 -1]

~~~~~~~~~~~~~~~~~~

Roll: 10
None
a


In [177]:
env = Environment()
warehouse,ordered_items = env.buildEnv()
env.print_grid(warehouse,ordered_items)
    
    #agentLocation starts at 0,0 in first episode
agentLocation = [0,0]
    
prcpt = percept(agentLocation,warehouse)
determine = prcpt.determine()
print(prcpt.getPercepts())
    
snsr = sensor(rand, agentLocation, prcpt)
snsr.setShelf()    
print(prcpt.getPercepts())
    


~~~~~~~~~~~~~~~~~~

Items ordered: ['D', 'F', 'G', 'J', 'A', 'E', 'B', 'I']

~~~~~~~~~~~~~~~~~~

[-1 -1  3 -1 -1 -1]
[-1  3 -1 -1  3 -1]
[ 3 -1  3 -1  3 -1]
[-1 -1 -1 -1 -1 -1]
[-1 -1  3 -1 -1 -1]
[-1 -1 -1  3 -1 -1]

~~~~~~~~~~~~~~~~~~

{'left': {'coord': [], 'value': ''}, 'right': {'coord': [0, 1], 'value': -1}, 'up': {'coord': [], 'value': ''}, 'down': {'coord': [1, 0], 'value': -1}, 'current': {'coord': [0, 0], 'value': -1}}
right
down
current
{'left': {'coord': [], 'value': ''}, 'right': {'coord': [0, 1], 'value': 3}, 'up': {'coord': [], 'value': ''}, 'down': {'coord': [1, 0], 'value': -1}, 'current': {'coord': [0, 0], 'value': -1}}
