# Project 1

## Pseudo Code

### Environment

Classes:
Grid
    Constructor: create a blank 6x6 2D array
Shelves
    Constructor: populate a random shelf configuration
        Random numbers if its the same then try again.
Agent Location
    Constructor: Random starting location that isn't on a Shelf

### Agent

Customer Order
    Constructor: Generate random number 1 - 10 and pick random unique shelf combo
Sensors
    Roll for sensor detection
    Add fake shelf
    Remove real shelf
    Detect shelves
Agent function
      If any of the grid positions in its neighborhood refers to an item ordered, then it moves to that grid position. If two or more neighboring positions contain ordered items, then the tie is broken by making a random choice between the positions involved. 
      If none of the neighboring positions contain ordered items, then a random choice is made to move to the next node.
Agent State
    
    
Agent Actuator
    Move agent
        left 
        right
        up
        down
Agent Items
    List of all items collected so far

In [ ]:
class agentFunction:
    
    
    
    def __init__(self, agentLocation, percept, customerOrder,acutator,randRange):
        self.location = agentLocation
        self.percept = percept
        self.order = customerOrder
        self.orderShelfLocations = []
        self.actuator = actuator
        self.random = randRange
        
        
        
    def setLocation(agentLocation):
        self.location = agentLocation
        
    def getLocation():
        return self.location
    
    def setPercept(percept):
        self.percept = percept
        
    def getPercept():
        return self.percept
    
    def addShelfLocation(location):
        self.orderShelfLocations.append(location)
        
    def getNextShelfLocation():
        return self.orderShelfLocations.pop(0)
    
    def getCurrentShelfLocation:
        return self.currentShelf
    
    def setCurrentShelfLocation(location):
        self.currentShelf = location
    #how to handle movement
    #have a current movement?
        
    def determineAction():
        if (self.percept.onOrderShelf()):
            self.actuator.collectItem()
            self.currentShelf = ""
        if (self.percept.shelfCount() == 0):
            if (len(self.orderShelfLocation) == 0):
                move = self.random(4)
                determineRandomMove(move)
            else:
                if(self.currentShelf != "")
                    self.actuator.move(self.currentShelf)
                else:
                    setCurrentShelfLocation(getNextShelfLocation())
                    self.actuator.move(self.currentShelf)
        elif (self.percept.shelfCount() >= 1):
            shelfLocations = self.percept.getShelfLocations()
            for i in shelfLocations:
                self.addShelfLocation(i)
            self.actuator.move(getNextShelfLocation())
            
    
    def determineRandomMove(move):
        if (move == 0):
            self.actuator.left()
        elif (move == 1):
            self.actuator.right()
        elif (move == 2):
            self.actuator.up()
        elif (move == 3):
            self.actuator.down()


In [6]:
#import libraries
import numpy as np
import random
class environment:
    line_sep = '\n~~~~~~~~~~~~~~~~~~\n'

    #Define the environment
    environment_rows = 6
    environment_columns = 6

    def print_grid():
        print("  "+" ".join(str(i)for i in range(6)))
        for y in range(6):
            print(str(y) + " " + " ".join(grid[y]))

    #Define rewards

    rewards = np.full((environment_rows, environment_columns), -1)

    #Give items their single character name
    item_A = 'A'
    item_B = 'B'
    item_C = 'C'
    item_D = 'D'
    item_E = 'E'
    item_F = 'F'
    item_G = 'G'
    item_H = 'H'
    item_I = 'I'
    item_J = 'J'

    #Generate random orders containing items A-J

    x = random.randint(1,10)

    items = [item_A,item_B, item_C, item_D, item_E, item_F, item_G, item_H, item_I, item_J]
    ordered_items = random.sample(items,x)
    print(line_sep)

    print('Items ordered:',ordered_items)

    print (line_sep)

    #Define location of agent and shelves with items location and rewards

    agentLocation = rewards[0,0] = 0

    item_A = 'A'
    if item_A in ordered_items:
                rewards [1,1] = 3
    else:
        rewards[1,1] = -1

    item_B = 'B'
    if item_B in ordered_items:
                rewards [2,2] = 3
    else:
        rewards[2,2] = -1

    item_C = 'C'
    if item_C in ordered_items:
                rewards [3,1] = 3
    else:
        rewards[3,1] = -1


    item_D = 'D'
    if item_D in ordered_items:
                rewards [0,2] = 3
    else:
        rewards[0,2] = -1


    item_E = 'E'
    if item_E in ordered_items:
                rewards [2,0] = 3
    else:
        rewards[2,0] = -1


    item_F = 'F'
    if item_F in ordered_items:
                rewards [4,2] = 3
    else:
        rewards[4,2] = -1


    item_G = 'G'
    if item_G in ordered_items:
                rewards [1,4] = 3
    else:
        rewards[1,4] = -1


    item_H = 'H'
    if item_H in ordered_items:
                rewards [4,5] = 3
    else:
        rewards[4,5] = -1


    item_I = 'I'
    if item_I in ordered_items:
                rewards [2,4] = 3
    else:
        rewards[2,4] = -1


    item_J = 'J'
    if item_J in ordered_items:
                rewards [5,3] = 3
    else:
        rewards[5,3] = -1

    #Define empty shelves locations
    empty = {}
    empty[0] = [1,3,4,5]
    empty[1] = [0,2,3,5]
    empty[2] = [1,3,5]
    empty[3] = [0,2,3,4,5]
    empty[4] = [0,1,3,4]
    empty[5] = [0,1,2,4,5]

    #Print rewards matrix
    for row in rewards:
        print(row)

    line_sep = '\n~~~~~~~~~~~~~~~~~~\n'
    print (line_sep)


~~~~~~~~~~~~~~~~~~

Items ordered: ['I', 'C', 'D', 'J', 'A']

~~~~~~~~~~~~~~~~~~

[ 0 -1  3 -1 -1 -1]
[-1  3 -1 -1 -1 -1]
[-1 -1 -1 -1  3 -1]
[-1  3 -1 -1 -1 -1]
[-1 -1 -1 -1 -1 -1]
[-1 -1 -1  3 -1 -1]

~~~~~~~~~~~~~~~~~~



In [5]:
class actuator:
    def __init__():
        
    def collectItem():
        
    def move():
        
    def left():
        
    def right():
        
    def up():
        
    def down():
        
    def addVisitedSpace():
        
        

IndentationError: expected an indented block (<ipython-input-5-27a370fcf8f3>, line 4)

In [ ]:
class percept:
    def __init__(self,currentlocation, envArray):
        self.percepts = dict(left=dict(coord=[],value=""), right=dict(coord=[],value=""), up=dict(coord=[],value=""), down=dict(coord=[],value=""), current=dict(coord=[],value=""))
        self.currentLocation = currentLocation
        self.env = envArray
        
    def determine():
        self.percepts["current"]["coord"] = currentLocation
        self.percepts["current"]["value"] = envArray[currentLocation[0]][currentLocation[1]]
        
        self.percepts["left"]["coord"] = [(currentLocation[0]-1),currentLocation[1]]
        self.percepts["left"]["value"] = envArray[currentLocation[0]][currentLocation[1]]
        
        self.percepts["right"]["coord"] = [(currentLocation[0]+1),currentLocation[1]]
        self.percepts["right"]["value"] = envArray[currentLocation[0]][currentLocation[1]]
        
        self.percepts["up"]["coord"] = [currentLocation[0],(currentLocation[1]-1)]
        self.percepts["up"]["value"] = envArray[currentLocation[0]][currentLocation[1]]
        
        self.percepts["down"]["coord"] = [currentLocation[0],(currentLocation[1]+1)]
        self.percepts["down"]["value"] = envArray[currentLocation[0]][currentLocation[1]]
    
    def onOrderShelf():
        if (self.percepts["current"]["value"] == 3):
            return true;
        return false
    
    def shelfCount():
        count = 0
        for i in self.percepts:
            if i["value"] == 3:
                count++
        return count
        
    def getShelfLocations():
        shelves = []
        for i in self.percepts:
            if i["value"] == 3:
                shelves.append(i["coord"])
        return shelves
        
    def getPercepts():
        return self.percepts
        

In [ ]:
class sensor:
    def __init__(self, random, agentlocation):
        self.random = random
        self.agentlocation = agentlocation
        
    def sensorRoll(percept, agentlocation):
        roll = self.random.RandomRoll(9)
        if roll == 8:
            percepts = percept.getPercepts(agentlocation)
            percepts = setEmptyShelf(percepts)
            return percept
            
        elif roll == 9:
            percepts = percept.getPercepts(agentlocation)
            percepts = setShelf(percept)
            return percepts
        else:
            percepts = percept.getPercepts(agentlocation)
            return percepts
    
    #need the percept to be an array of dictionaries
    def setEmptyShelf(percept):
        shelves = []
        for (i in percept):
            if (percept[i] == 3):
                shelves.append(i)
            
        roll = self.random.RandomRoll(len(shelves))
        key = shelves[roll]
        percept[key] = -1
        return percept    
    
    def setShelf(percept):
        empty = []
        for (i in percept):
            if (percept[i] == -1):
                empty.append(i)
            
        roll = self.random.RandomRoll(len(empty))
        key = empty[roll]
        percept[key] = 3
        return percept 

In [ ]:
class stats:
    

In [ ]:
def main():
    